### ISSUE TITLE
Clone function should "guess" new folder name

### ISSUE THREAD

**Issue by Epiktetus** [DudleyDoorite/EEMForms#6]
As simple as looking to see if the last two characters are digits and incrementing by one.
01 becomes 02
19 becomes 20

or adding 00 if they aren't
xyz becomes xyz 00

Shouldn't have to worry about 99 or single digits as that *shouldn't* ever happen

**Comment by DudleyDoorite** [comment]
Added Static Call GetNextFolder(string folder)
