### ISSUE TITLE
Remember last selected Episode

### ISSUE THREAD

**Issue by Epiktetus** [DudleyDoorite/EEMForms#9]
Each episode switch save to the settings file the Episode Folder name
Then on form load during initial episode folder scan if the saved setting matches the loaded node, select that node.

**Comment by DudleyDoorite** [comment]
Do you want it to load the last selected episode when you restart the app?

**Comment by Epiktetus** [comment]
Yeah, I tend to work on one project for a while and start the app several times, so it'd be handy to not have to find the one I'm working on in the list each launch.

**Comment by Epiktetus** [comment]
It's kinda working now and is probably good enough.
